use super::definition_schema::Definition;

#[derive(
    serde::Serialize, serde::Deserialize, PartialEq, strum::Display, strum::VariantArray, Clone,
)]
#[strum(serialize_all = "snake_case")]
pub enum DefinitionAttribute {
    Name,
    Category,
    Type,
    Mass,
    Value,
    Flags,
    Tags,
    PhysCollisionDampen,
    AudioFilenameStart,
    AudioFilenameLoop,
    AudioFilenameEnd,
    AudioFilenameStartB,
    AudioFilenameLoopB,
    AudioFilenameEndB,
    AudioGain,
    MeshDataName,
    Mesh0Name,
    Mesh1Name,
    Mesh2Name,
    MeshEditorOnlyName,
    BlockType,
    ChildName,
    ExtenderName,
    ConstraintType,
    ConstraintAxis,
    ConstraintRangeOfMotion,
    MaxMotorForce,
    MaxMotorSpeed,
    CableRadius,
    CableLength,
    SeatType,
    SeatPose,
    SeatHealthPerSec,
    BuoyRadius,
    BuoyFactor,
    BuoyForce,
    ForceEmitterMaxForce,
    ForceEmitterMaxVector,
    ForceEmitterDefaultPitch,
    ForceEmitterBladeHeight,
    ForceEmitterRotationSpeed,
    ForceEmitterBladePhysicsLength,
    ForceEmitterBladeEfficiency,
    ForceEmitterEfficiency,
    EngineMaxForce,
    EngineFrictionlessForce,
    TransConnType,
    TransType,
    WheelRadius,
    WheelWidth,
    WheelWishboneLength,
    WheelSuspensionHeight,
    WheelWishboneMargin,
    WheelSuspensionOffset,
    WheelWishboneOffset,
    WheelType,
    ButtonType,
    LightIntensity,
    LightRange,
    LightIesMap,
    LightFov,
    LightType,
    DoorLowerLimit,
    DoorUpperLimit,
    DoorFlipped,
    CustomDoorType,
    DoorSideDist,
    DoorUpDist,
    DynamicMinRotation,
    DynamicMaxRotation,
    LogicGateType,
    LogicGateSubtype,
    IndicatorType,
    ConnectorType,
    MagnetForce,
    GyroType,
    RewardTier,
    Revision,
    RudderSurfaceArea,
    PumpPressure,
    MPumpPressure,
    WaterComponentType,
    TorqueComponentType,
    JetEngineComponentType,
    ParticleSpeed,
    InventoryType,
    InventoryDefaultOutfit,
    InventoryClass,
    InventoryDefaultItem,
    ElectricType,
    ElectricChargeCapacity,
    ElectricMagnitude,
    CompositeType,
    CameraFovMin,
    CameraFovMax,
    MonitorBorder,
    MonitorInset,
    WeaponType,
    WeaponClass,
    WeaponBeltType,
    WeaponAmmoCapacity,
    WeaponAmmoFeed,
    WeaponBarrelLengthVoxels,
    RxRange,
    RxLength,
    RocketType,
    RadarRange,
    RadarSpeed,
    EngineModuleType,
    SteamComponentType,
    SteamComponentCapacity,
    NuclearComponentType,
    RadarType,
    PistonLen,
    PistonCam,
    DataLoggerComponentType,
    MetadataComponentType,
    OilComponentType,
    ToolType,
}

impl DefinitionAttribute {
    pub fn get_value(&self, d: &Definition) -> Option<DefinitionAttributeValue> {
        match self {
            Self::Name => attr_val(&d.name),
            Self::Category => attr_val(&d.category),
            Self::Type => attr_val(&d.definition_type),
            Self::Mass => attr_val(&d.mass),
            Self::Value => attr_val(&d.value),
            Self::Flags => attr_val(&d.flags),
            Self::Tags => attr_val(&d.tags),
            Self::PhysCollisionDampen => attr_val(&d.phys_collision_dampen),
            Self::AudioFilenameStart => attr_val(&d.audio_filename_start),
            Self::AudioFilenameLoop => attr_val(&d.audio_filename_loop),
            Self::AudioFilenameEnd => attr_val(&d.audio_filename_end),
            Self::AudioFilenameStartB => attr_val(&d.audio_filename_start_b),
            Self::AudioFilenameLoopB => attr_val(&d.audio_filename_loop_b),
            Self::AudioFilenameEndB => attr_val(&d.audio_filename_end_b),
            Self::AudioGain => attr_val(&d.audio_gain),
            Self::MeshDataName => attr_val(&d.mesh_data_name),
            Self::Mesh0Name => attr_val(&d.mesh_0_name),
            Self::Mesh1Name => attr_val(&d.mesh_1_name),
            Self::Mesh2Name => attr_val(&d.mesh_2_name),
            Self::MeshEditorOnlyName => attr_val(&d.mesh_editor_only_name),
            Self::BlockType => attr_val(&d.block_type),
            Self::ChildName => attr_val(&d.child_name),
            Self::ExtenderName => attr_val(&d.extender_name),
            Self::ConstraintType => attr_val(&d.constraint_type),
            Self::ConstraintAxis => attr_val(&d.constraint_axis),
            Self::ConstraintRangeOfMotion => attr_val(&d.constraint_range_of_motion),
            Self::MaxMotorForce => attr_val(&d.max_motor_force),
            Self::MaxMotorSpeed => attr_val(&d.max_motor_speed),
            Self::CableRadius => attr_val(&d.cable_radius),
            Self::CableLength => attr_val(&d.cable_length),
            Self::SeatType => attr_val(&d.seat_type),
            Self::SeatPose => attr_val(&d.seat_pose),
            Self::SeatHealthPerSec => attr_val(&d.seat_health_per_sec),
            Self::BuoyRadius => attr_val(&d.buoy_radius),
            Self::BuoyFactor => attr_val(&d.buoy_factor),
            Self::BuoyForce => attr_val(&d.buoy_force),
            Self::ForceEmitterMaxForce => attr_val(&d.force_emitter_max_force),
            Self::ForceEmitterMaxVector => attr_val(&d.force_emitter_max_vector),
            Self::ForceEmitterDefaultPitch => attr_val(&d.force_emitter_default_pitch),
            Self::ForceEmitterBladeHeight => attr_val(&d.force_emitter_blade_height),
            Self::ForceEmitterRotationSpeed => attr_val(&d.force_emitter_rotation_speed),
            Self::ForceEmitterBladePhysicsLength => attr_val(&d.force_emitter_blade_physics_length),
            Self::ForceEmitterBladeEfficiency => attr_val(&d.force_emitter_blade_efficiency),
            Self::ForceEmitterEfficiency => attr_val(&d.force_emitter_efficiency),
            Self::EngineMaxForce => attr_val(&d.engine_max_force),
            Self::EngineFrictionlessForce => attr_val(&d.engine_frictionless_force),
            Self::TransConnType => attr_val(&d.trans_conn_type),
            Self::TransType => attr_val(&d.trans_type),
            Self::WheelRadius => attr_val(&d.wheel_radius),
            Self::WheelWidth => attr_val(&d.wheel_width),
            Self::WheelWishboneLength => attr_val(&d.wheel_wishbone_length),
            Self::WheelSuspensionHeight => attr_val(&d.wheel_suspension_height),
            Self::WheelWishboneMargin => attr_val(&d.wheel_wishbone_margin),
            Self::WheelSuspensionOffset => attr_val(&d.wheel_suspension_offset),
            Self::WheelWishboneOffset => attr_val(&d.wheel_wishbone_offset),
            Self::WheelType => attr_val(&d.wheel_type),
            Self::ButtonType => attr_val(&d.button_type),
            Self::LightIntensity => attr_val(&d.light_intensity),
            Self::LightRange => attr_val(&d.light_range),
            Self::LightIesMap => attr_val(&d.light_ies_map),
            Self::LightFov => attr_val(&d.light_fov),
            Self::LightType => attr_val(&d.light_type),
            Self::DoorLowerLimit => attr_val(&d.door_lower_limit),
            Self::DoorUpperLimit => attr_val(&d.door_upper_limit),
            Self::DoorFlipped => attr_val(&d.door_flipped),
            Self::CustomDoorType => attr_val(&d.custom_door_type),
            Self::DoorSideDist => attr_val(&d.door_side_dist),
            Self::DoorUpDist => attr_val(&d.door_up_dist),
            Self::DynamicMinRotation => attr_val(&d.dynamic_min_rotation),
            Self::DynamicMaxRotation => attr_val(&d.dynamic_max_rotation),
            Self::LogicGateType => attr_val(&d.logic_gate_type),
            Self::LogicGateSubtype => attr_val(&d.logic_gate_subtype),
            Self::IndicatorType => attr_val(&d.indicator_type),
            Self::ConnectorType => attr_val(&d.connector_type),
            Self::MagnetForce => attr_val(&d.magnet_force),
            Self::GyroType => attr_val(&d.gyro_type),
            Self::RewardTier => attr_val(&d.reward_tier),
            Self::Revision => attr_val(&d.revision),
            Self::RudderSurfaceArea => attr_val(&d.rudder_surface_area),
            Self::PumpPressure => attr_val(&d.pump_pressure),
            Self::MPumpPressure => attr_val(&d.m_pump_pressure),
            Self::WaterComponentType => attr_val(&d.water_component_type),
            Self::TorqueComponentType => attr_val(&d.torque_component_type),
            Self::JetEngineComponentType => attr_val(&d.jet_engine_component_type),
            Self::ParticleSpeed => attr_val(&d.particle_speed),
            Self::InventoryType => attr_val(&d.inventory_type),
            Self::InventoryDefaultOutfit => attr_val(&d.inventory_default_outfit),
            Self::InventoryClass => attr_val(&d.inventory_class),
            Self::InventoryDefaultItem => attr_val(&d.inventory_default_item),
            Self::ElectricType => attr_val(&d.electric_type),
            Self::ElectricChargeCapacity => attr_val(&d.electric_charge_capacity),
            Self::ElectricMagnitude => attr_val(&d.electric_magnitude),
            Self::CompositeType => attr_val(&d.composite_type),
            Self::CameraFovMin => attr_val(&d.camera_fov_min),
            Self::CameraFovMax => attr_val(&d.camera_fov_max),
            Self::MonitorBorder => attr_val(&d.monitor_border),
            Self::MonitorInset => attr_val(&d.monitor_inset),
            Self::WeaponType => attr_val(&d.weapon_type),
            Self::WeaponClass => attr_val(&d.weapon_class),
            Self::WeaponBeltType => attr_val(&d.weapon_belt_type),
            Self::WeaponAmmoCapacity => attr_val(&d.weapon_ammo_capacity),
            Self::WeaponAmmoFeed => attr_val(&d.weapon_ammo_feed),
            Self::WeaponBarrelLengthVoxels => attr_val(&d.weapon_barrel_length_voxels),
            Self::RxRange => attr_val(&d.rx_range),
            Self::RxLength => attr_val(&d.rx_length),
            Self::RocketType => attr_val(&d.rocket_type),
            Self::RadarRange => attr_val(&d.radar_range),
            Self::RadarSpeed => attr_val(&d.radar_speed),
            Self::EngineModuleType => attr_val(&d.engine_module_type),
            Self::SteamComponentType => attr_val(&d.steam_component_type),
            Self::SteamComponentCapacity => attr_val(&d.steam_component_capacity),
            Self::NuclearComponentType => attr_val(&d.nuclear_component_type),
            Self::RadarType => attr_val(&d.radar_type),
            Self::PistonLen => attr_val(&d.piston_len),
            Self::PistonCam => attr_val(&d.piston_cam),
            Self::DataLoggerComponentType => attr_val(&d.data_logger_component_type),
            Self::MetadataComponentType => attr_val(&d.metadata_component_type),
            Self::OilComponentType => attr_val(&d.oil_component_type),
            Self::ToolType => attr_val(&d.tool_type),
        }
    }
}

pub struct DefinitionAttributeValue {
    pub debug_str: String,
    pub is_default: bool,
}

fn attr_val<T: std::fmt::Debug + Default + PartialEq>(
    val: &Option<T>,
) -> Option<DefinitionAttributeValue> {
    val.as_ref().map(|val| DefinitionAttributeValue {
        debug_str: format!("{:?}", val),
        is_default: *val == T::default(),
    })
}
